
import React from 'react';

const HomePage: React.FC = () => {
  return (
    <div className="flex items-center justify-center h-full">
      <div className="text-center p-12 bg-white rounded-xl shadow-lg max-w-2xl mx-auto">
        <div className="mb-4">
          <svg className="w-24 h-24 mx-auto text-emerald-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v11.494m-5.247-8.493l10.494 0M4.753 12h14.494" /></svg>
        </div>
        <h1 className="text-4xl font-bold text-gray-800 mb-4">Welcome to the GSheet AI Tutor</h1>
        <p className="text-lg text-gray-600 mb-6">
          Select a topic from the sidebar to get started. Each guide is generated by AI to provide you with a comprehensive, step-by-step tutorial.
        </p>
        <p className="text-gray-500">
          Whether you're a beginner or looking to master advanced features, there's something here for you.
        </p>
      </div>
    </div>
  );
};

export default HomePage;
